name: docker

permissions: # Principle of least privilege
  contents: read
  actions: read
  packages: write # Required for pushing Docker images to GHCR

on:
  workflow_dispatch:
jobs:
  build-docker-images:
    name: build-docker-images
    runs-on: ubuntu-latest
    env:
      BUILD_MODE: release
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      
      # - name: Free disk space (Ubuntu)
      #   # https://github.com/jlumbroso/free-disk-space
      #   uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      #   with:
      #     tool-cache: true
      #     android: false
      #     dotnet: false
      #     haskell: false
      #     large-packages: true
      #     docker-images: true
      #     swap-storage: true

      - name: Set up QEMU
        # https://github.com/docker/setup-qemu-action
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to GHCR
        # https://github.com/docker/login-action
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build image
        id: docker_build_cpppython_latest
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          file: ".docker/cpppython.dockerfile"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cpppython:latest
          cache-from: type=gha
          cache-to: type=gha
          platforms: |
            linux/amd64
            linux/arm64
          build-args: |
            VARIANT=ubuntu-24.04
            MOUNTPATH=/docker_data
            USERNAME=root

      - name: Digest image
        run: echo ${{ steps.docker_build_cpppython_latest.outputs.digest }}
